context:
  -
    is_404: true
    is_attachment: true
    is_author: true
    is_category: true
    is_comments_popup: true
    is_date: true
    is_front_page: true
    is_home: true
    is_page: true
    is_preview: true
    is_search: true
    is_single: true
    is_tag: true
    is_tax: true
menu: {  }
post: {  }
taxonomy: {  }
archive: {  }
